"""SQLAlchemy ORM models: the shape of the data as PostgreSQL stores it.

These are deliberately separate from the Pydantic schemas in schemas.py. The ORM
model describes the table; the schema describes the API contract. Keeping them apart
means a column can be added, indexed or renamed without silently changing what the
API returns.
"""

from datetime import datetime

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Prediction(Base):
    """One stored answer produced by the model for one uploaded image."""

    __tablename__ = "predictions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Bounded: a filename is short by nature, and a length limit keeps a malicious
    # client from storing megabytes in this column.
    filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # Unbounded: the question is user-supplied and the answer is generated prose;
    # in PostgreSQL, Text has no performance penalty over Varchar.
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)

    duration_ms: Mapped[int] = mapped_column(Integer, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        # timezone=True maps to timestamptz. Without it PostgreSQL stores a naive
        # timestamp and the value becomes ambiguous the moment the container's
        # timezone differs from the reader's.
        DateTime(timezone=True),
        # Generated by PostgreSQL, not by Python: the database clock is the single
        # source of truth even if several application containers are running.
        server_default=func.now(),
        nullable=False,
        # GET /history sorts on this column, so it is worth indexing.
        index=True,
    )

    def __repr__(self) -> str:
        return f"<Prediction id={self.id} filename={self.filename!r}>"
